apiVersion: v1
kind: Template
metadata:
  name: s2i-thoth
  annotations:
    description: >
      This is Thoth s2i-thoth-ubi8-py36 BuildConfig, this template is meant to be used by bots,
      but could also be used by humans...
    openshift.io/display-name: Thoth s2i-thoth-ubi8-py36 BuildConfig
    version: 0.6.0
    tags: poc,thoth,ai-stacks,s2i-thoth-ubi8-py36
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: >
      This is Thoth s2i-thoth-ubi8-py36 BuildConfig, this template is meant to be used by bots,
      but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.6.0
  labels:
    template: s2i-thoth-buildconfig
    app: thoth
    component: s2i-thoth

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: thoth
        component: s2i-thoth
      name: s2i-thoth-ubi8-py36
    spec:
      resources:
        limits:
          cpu: 2000m
          memory: 768Mi
        requests:
          cpu: 2000m
          memory: 768Mi
      output:
        to:
          kind: ImageStreamTag
          name: "s2i-thoth-ubi8-py36:${IMAGE_STREAM_TAG}"
      runPolicy: Serial
      source:
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: "ubi8-py36/Dockerfile"
          noCache: true
        env:
          - name: ENABLE_PIPENV
            value: "1"
          - name: UPGRADE_PIP_TO_LATEST
            value: ""
        type: Docker
      triggers:
        - imageChange: {}
          type: ImageChange

parameters:
  - description: Git repository for Thoth's s2i-thoth
    displayName: Thoth s2i-thoth git repository
    required: true
    name: GITHUB_URL
    value: "https://github.com/harshad16/s2i-thoth"

  - description: Git repository for Thoth's s2i-thoth
    displayName: Thoth s2i-thoth git reference
    required: true
    name: GITHUB_REF
    value: "p9-openshift"

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"
